/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq;


import com.ns.vertx.pg.jooq.tables.Author;
import com.ns.vertx.pg.jooq.tables.AuthorBook;
import com.ns.vertx.pg.jooq.tables.Book;
import com.ns.vertx.pg.jooq.tables.Category;
import com.ns.vertx.pg.jooq.tables.CategoryBook;
import com.ns.vertx.pg.jooq.tables.OrderItem;
import com.ns.vertx.pg.jooq.tables.Orders;
import com.ns.vertx.pg.jooq.tables.Role;
import com.ns.vertx.pg.jooq.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTHOR_PKEY = Indexes0.AUTHOR_PKEY;
    public static final Index AUTHOR_BOOK_PKEY = Indexes0.AUTHOR_BOOK_PKEY;
    public static final Index BOOK_PKEY = Indexes0.BOOK_PKEY;
    public static final Index CATEGORY_PKEY = Indexes0.CATEGORY_PKEY;
    public static final Index CATEGORY_BOOK_PKEY = Indexes0.CATEGORY_BOOK_PKEY;
    public static final Index ORDER_ITEM_PKEY = Indexes0.ORDER_ITEM_PKEY;
    public static final Index ORDERS_PKEY = Indexes0.ORDERS_PKEY;
    public static final Index ROLE_PKEY = Indexes0.ROLE_PKEY;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AUTHOR_PKEY = Internal.createIndex("author_pkey", Author.AUTHOR, new OrderField[] { Author.AUTHOR.AUTHOR_ID }, true);
        public static Index AUTHOR_BOOK_PKEY = Internal.createIndex("author_book_pkey", AuthorBook.AUTHOR_BOOK, new OrderField[] { AuthorBook.AUTHOR_BOOK.AUTHOR_ID, AuthorBook.AUTHOR_BOOK.BOOK_ID }, true);
        public static Index BOOK_PKEY = Internal.createIndex("book_pkey", Book.BOOK, new OrderField[] { Book.BOOK.BOOK_ID }, true);
        public static Index CATEGORY_PKEY = Internal.createIndex("category_pkey", Category.CATEGORY, new OrderField[] { Category.CATEGORY.CATEGORY_ID }, true);
        public static Index CATEGORY_BOOK_PKEY = Internal.createIndex("category_book_pkey", CategoryBook.CATEGORY_BOOK, new OrderField[] { CategoryBook.CATEGORY_BOOK.CATEGORY_ID, CategoryBook.CATEGORY_BOOK.BOOK_ID }, true);
        public static Index ORDER_ITEM_PKEY = Internal.createIndex("order_item_pkey", OrderItem.ORDER_ITEM, new OrderField[] { OrderItem.ORDER_ITEM.ORDER_ITEM_ID }, true);
        public static Index ORDERS_PKEY = Internal.createIndex("orders_pkey", Orders.ORDERS, new OrderField[] { Orders.ORDERS.ORDER_ID }, true);
        public static Index ROLE_PKEY = Internal.createIndex("role_pkey", Role.ROLE, new OrderField[] { Role.ROLE.ROLE_ID }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.USER_ID }, true);
    }
}
