/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq;


import com.ns.vertx.pg.jooq.routines.GetAllOrders;
import com.ns.vertx.pg.jooq.routines.GetBookByBookId;
import com.ns.vertx.pg.jooq.routines.GetOrderByOrderId;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.get_all_orders</code>
     */
    public static String getAllOrders(Configuration configuration) {
        GetAllOrders f = new GetAllOrders();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.get_all_orders</code> as a field.
     */
    public static Field<String> getAllOrders() {
        GetAllOrders f = new GetAllOrders();

        return f.asField();
    }

    /**
     * Call <code>public.get_book_by_book_id</code>
     */
    public static String getBookByBookId(Configuration configuration, String bId) {
        GetBookByBookId f = new GetBookByBookId();
        f.setBId(bId);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.get_book_by_book_id</code> as a field.
     */
    public static Field<String> getBookByBookId(String bId) {
        GetBookByBookId f = new GetBookByBookId();
        f.setBId(bId);

        return f.asField();
    }

    /**
     * Get <code>public.get_book_by_book_id</code> as a field.
     */
    public static Field<String> getBookByBookId(Field<String> bId) {
        GetBookByBookId f = new GetBookByBookId();
        f.setBId(bId);

        return f.asField();
    }

    /**
     * Call <code>public.get_order_by_order_id</code>
     */
    public static String getOrderByOrderId(Configuration configuration, String oId) {
        GetOrderByOrderId f = new GetOrderByOrderId();
        f.setOId(oId);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.get_order_by_order_id</code> as a field.
     */
    public static Field<String> getOrderByOrderId(String oId) {
        GetOrderByOrderId f = new GetOrderByOrderId();
        f.setOId(oId);

        return f.asField();
    }

    /**
     * Get <code>public.get_order_by_order_id</code> as a field.
     */
    public static Field<String> getOrderByOrderId(Field<String> oId) {
        GetOrderByOrderId f = new GetOrderByOrderId();
        f.setOId(oId);

        return f.asField();
    }
}
