/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.author_author_id_seq</code>
     */
    public static final Sequence<Long> AUTHOR_AUTHOR_ID_SEQ = new SequenceImpl<Long>("author_author_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.book_book_id_seq</code>
     */
    public static final Sequence<Long> BOOK_BOOK_ID_SEQ = new SequenceImpl<Long>("book_book_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.category_category_id_seq</code>
     */
    public static final Sequence<Long> CATEGORY_CATEGORY_ID_SEQ = new SequenceImpl<Long>("category_category_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.order_item_order_item_id_seq</code>
     */
    public static final Sequence<Long> ORDER_ITEM_ORDER_ITEM_ID_SEQ = new SequenceImpl<Long>("order_item_order_item_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.orders_order_id_seq</code>
     */
    public static final Sequence<Long> ORDERS_ORDER_ID_SEQ = new SequenceImpl<Long>("orders_order_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.role_role_id_seq</code>
     */
    public static final Sequence<Long> ROLE_ROLE_ID_SEQ = new SequenceImpl<Long>("role_role_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.users_user_id_seq</code>
     */
    public static final Sequence<Long> USERS_USER_ID_SEQ = new SequenceImpl<Long>("users_user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
