/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.author_author_id_seq</code>
     */
    public static final Sequence<Long> AUTHOR_AUTHOR_ID_SEQ = Internal.createSequence("author_author_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.book_book_id_seq</code>
     */
    public static final Sequence<Long> BOOK_BOOK_ID_SEQ = Internal.createSequence("book_book_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.category_category_id_seq</code>
     */
    public static final Sequence<Long> CATEGORY_CATEGORY_ID_SEQ = Internal.createSequence("category_category_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.order_item_order_item_id_seq</code>
     */
    public static final Sequence<Long> ORDER_ITEM_ORDER_ITEM_ID_SEQ = Internal.createSequence("order_item_order_item_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.orders_order_id_seq</code>
     */
    public static final Sequence<Long> ORDERS_ORDER_ID_SEQ = Internal.createSequence("orders_order_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.role_role_id_seq</code>
     */
    public static final Sequence<Long> ROLE_ROLE_ID_SEQ = Internal.createSequence("role_role_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.users_user_id_seq</code>
     */
    public static final Sequence<Long> USERS_USER_ID_SEQ = Internal.createSequence("users_user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
