/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAuthor extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.author.author_id</code>.
     */
    public IAuthor setAuthorId(Long value);

    /**
     * Getter for <code>public.author.author_id</code>.
     */
    public Long getAuthorId();

    /**
     * Setter for <code>public.author.first_name</code>.
     */
    public IAuthor setFirstName(String value);

    /**
     * Getter for <code>public.author.first_name</code>.
     */
    public String getFirstName();

    /**
     * Setter for <code>public.author.last_name</code>.
     */
    public IAuthor setLastName(String value);

    /**
     * Getter for <code>public.author.last_name</code>.
     */
    public String getLastName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IAuthor
     */
    public void from(com.ns.vertx.pg.jooq.tables.interfaces.IAuthor from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IAuthor
     */
    public <E extends com.ns.vertx.pg.jooq.tables.interfaces.IAuthor> E into(E into);

    @Override
    public default IAuthor fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setAuthorId(json.getLong("author_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("author_id","java.lang.Long",e);
        }
        try {
            setFirstName(json.getString("first_name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("first_name","java.lang.String",e);
        }
        try {
            setLastName(json.getString("last_name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("last_name","java.lang.String",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("author_id",getAuthorId());
        json.put("first_name",getFirstName());
        json.put("last_name",getLastName());
        return json;
    }

}
