/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IBook extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.book.book_id</code>.
     */
    public IBook setBookId(Long value);

    /**
     * Getter for <code>public.book.book_id</code>.
     */
    public Long getBookId();

    /**
     * Setter for <code>public.book.title</code>.
     */
    public IBook setTitle(String value);

    /**
     * Getter for <code>public.book.title</code>.
     */
    public String getTitle();

    /**
     * Setter for <code>public.book.price</code>.
     */
    public IBook setPrice(Double value);

    /**
     * Getter for <code>public.book.price</code>.
     */
    public Double getPrice();

    /**
     * Setter for <code>public.book.amount</code>.
     */
    public IBook setAmount(Integer value);

    /**
     * Getter for <code>public.book.amount</code>.
     */
    public Integer getAmount();

    /**
     * Setter for <code>public.book.is_deleted</code>.
     */
    public IBook setIsDeleted(Boolean value);

    /**
     * Getter for <code>public.book.is_deleted</code>.
     */
    public Boolean getIsDeleted();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IBook
     */
    public void from(com.ns.vertx.pg.jooq.tables.interfaces.IBook from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IBook
     */
    public <E extends com.ns.vertx.pg.jooq.tables.interfaces.IBook> E into(E into);

    @Override
    public default IBook fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setBookId(json.getLong("book_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("book_id","java.lang.Long",e);
        }
        try {
            setTitle(json.getString("title"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("title","java.lang.String",e);
        }
        try {
            setPrice(json.getDouble("price"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("price","java.lang.Double",e);
        }
        try {
            setAmount(json.getInteger("amount"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("amount","java.lang.Integer",e);
        }
        try {
            setIsDeleted(json.getBoolean("is_deleted"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("is_deleted","java.lang.Boolean",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("book_id",getBookId());
        json.put("title",getTitle());
        json.put("price",getPrice());
        json.put("amount",getAmount());
        json.put("is_deleted",getIsDeleted());
        return json;
    }

}
