/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICategory extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.category.category_id</code>.
     */
    public ICategory setCategoryId(Long value);

    /**
     * Getter for <code>public.category.category_id</code>.
     */
    public Long getCategoryId();

    /**
     * Setter for <code>public.category.name</code>.
     */
    public ICategory setName(String value);

    /**
     * Getter for <code>public.category.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.category.is_deleted</code>.
     */
    public ICategory setIsDeleted(Boolean value);

    /**
     * Getter for <code>public.category.is_deleted</code>.
     */
    public Boolean getIsDeleted();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICategory
     */
    public void from(ICategory from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICategory
     */
    public <E extends ICategory> E into(E into);

    @Override
    public default ICategory fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setCategoryId(json.getLong("category_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("category_id","java.lang.Long",e);
        }
        try {
            setName(json.getString("name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("name","java.lang.String",e);
        }
        try {
            setIsDeleted(json.getBoolean("is_deleted"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("is_deleted","java.lang.Boolean",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("category_id",getCategoryId());
        json.put("name",getName());
        json.put("is_deleted",getIsDeleted());
        return json;
    }

}
