/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IOrderItem extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.order_item.order_item_id</code>.
     */
    public IOrderItem setOrderItemId(Long value);

    /**
     * Getter for <code>public.order_item.order_item_id</code>.
     */
    public Long getOrderItemId();

    /**
     * Setter for <code>public.order_item.amount</code>.
     */
    public IOrderItem setAmount(Integer value);

    /**
     * Getter for <code>public.order_item.amount</code>.
     */
    public Integer getAmount();

    /**
     * Setter for <code>public.order_item.book_id</code>.
     */
    public IOrderItem setBookId(Long value);

    /**
     * Getter for <code>public.order_item.book_id</code>.
     */
    public Long getBookId();

    /**
     * Setter for <code>public.order_item.order_id</code>.
     */
    public IOrderItem setOrderId(Long value);

    /**
     * Getter for <code>public.order_item.order_id</code>.
     */
    public Long getOrderId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IOrderItem
     */
    public void from(IOrderItem from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IOrderItem
     */
    public <E extends IOrderItem> E into(E into);

    @Override
    public default IOrderItem fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setOrderItemId(json.getLong("order_item_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("order_item_id","java.lang.Long",e);
        }
        try {
            setAmount(json.getInteger("amount"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("amount","java.lang.Integer",e);
        }
        try {
            setBookId(json.getLong("book_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("book_id","java.lang.Long",e);
        }
        try {
            setOrderId(json.getLong("order_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("order_id","java.lang.Long",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("order_item_id",getOrderItemId());
        json.put("amount",getAmount());
        json.put("book_id",getBookId());
        json.put("order_id",getOrderId());
        return json;
    }

}
