/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IRole extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.role.role_id</code>.
     */
    public IRole setRoleId(Long value);

    /**
     * Getter for <code>public.role.role_id</code>.
     */
    public Long getRoleId();

    /**
     * Setter for <code>public.role.name</code>.
     */
    public IRole setName(String value);

    /**
     * Getter for <code>public.role.name</code>.
     */
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IRole
     */
    public void from(com.ns.vertx.pg.jooq.tables.interfaces.IRole from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IRole
     */
    public <E extends com.ns.vertx.pg.jooq.tables.interfaces.IRole> E into(E into);

    @Override
    public default IRole fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setRoleId(json.getLong("role_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("role_id","java.lang.Long",e);
        }
        try {
            setName(json.getString("name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("name","java.lang.String",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("role_id",getRoleId());
        json.put("name",getName());
        return json;
    }

}
