/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.daos;


import com.ns.vertx.pg.jooq.tables.AuthorBook;
import com.ns.vertx.pg.jooq.tables.records.AuthorBookRecord;

import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;


import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorBookDao extends AbstractReactiveVertxDAO<AuthorBookRecord, com.ns.vertx.pg.jooq.tables.pojos.AuthorBook, Record2<Long, Long>, Future<List<com.ns.vertx.pg.jooq.tables.pojos.AuthorBook>>, Future<com.ns.vertx.pg.jooq.tables.pojos.AuthorBook>, Future<Integer>, Future<Record2<Long, Long>>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<AuthorBookRecord,com.ns.vertx.pg.jooq.tables.pojos.AuthorBook,Record2<Long, Long>> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the POSTGREs types.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public AuthorBookDao(Configuration configuration, io.vertx.sqlclient.SqlClient delegate) {
        super(AuthorBook.AUTHOR_BOOK, com.ns.vertx.pg.jooq.tables.pojos.AuthorBook.class, new ReactiveClassicQueryExecutor<AuthorBookRecord,com.ns.vertx.pg.jooq.tables.pojos.AuthorBook,Record2<Long, Long>>(configuration,delegate,com.ns.vertx.pg.jooq.tables.mappers.RowMappers.getAuthorBookMapper()));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Long, Long> getId(com.ns.vertx.pg.jooq.tables.pojos.AuthorBook object) {
        return compositeKeyRecord(object.getAuthorId(), object.getBookId());
    }

    /**
     * Find records that have <code>book_id IN (values)</code> asynchronously
     */
    public Future<List<com.ns.vertx.pg.jooq.tables.pojos.AuthorBook>> findManyByBookId(List<Long> values) {
        return findManyByCondition(AuthorBook.AUTHOR_BOOK.BOOK_ID.in(values));
    }

    @Override
    public ReactiveClassicQueryExecutor<AuthorBookRecord,com.ns.vertx.pg.jooq.tables.pojos.AuthorBook,Record2<Long, Long>> queryExecutor(){
        return (ReactiveClassicQueryExecutor<AuthorBookRecord,com.ns.vertx.pg.jooq.tables.pojos.AuthorBook,Record2<Long, Long>>) super.queryExecutor();
    }
}
