/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.daos;


import com.ns.vertx.pg.jooq.tables.Role;
import com.ns.vertx.pg.jooq.tables.records.RoleRecord;

import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;


import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleDao extends AbstractReactiveVertxDAO<RoleRecord, com.ns.vertx.pg.jooq.tables.pojos.Role, Long, Future<List<com.ns.vertx.pg.jooq.tables.pojos.Role>>, Future<com.ns.vertx.pg.jooq.tables.pojos.Role>, Future<Integer>, Future<Long>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<RoleRecord,com.ns.vertx.pg.jooq.tables.pojos.Role,Long> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the POSTGREs types.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public RoleDao(Configuration configuration, io.vertx.sqlclient.SqlClient delegate) {
        super(Role.ROLE, com.ns.vertx.pg.jooq.tables.pojos.Role.class, new ReactiveClassicQueryExecutor<RoleRecord,com.ns.vertx.pg.jooq.tables.pojos.Role,Long>(configuration,delegate,com.ns.vertx.pg.jooq.tables.mappers.RowMappers.getRoleMapper()));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.ns.vertx.pg.jooq.tables.pojos.Role object) {
        return object.getRoleId();
    }

    /**
     * Find records that have <code>name IN (values)</code> asynchronously
     */
    public Future<List<com.ns.vertx.pg.jooq.tables.pojos.Role>> findManyByName(List<String> values) {
        return findManyByCondition(Role.ROLE.NAME.in(values));
    }

    @Override
    public ReactiveClassicQueryExecutor<RoleRecord,com.ns.vertx.pg.jooq.tables.pojos.Role,Long> queryExecutor(){
        return (ReactiveClassicQueryExecutor<RoleRecord,com.ns.vertx.pg.jooq.tables.pojos.Role,Long>) super.queryExecutor();
    }
}
