/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.pojos;


import com.ns.vertx.pg.jooq.tables.interfaces.IAuthor;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements VertxPojo, IAuthor {

    private static final long serialVersionUID = -961112301;

    private Long   authorId;
    private String firstName;
    private String lastName;

    public Author() {}

    public Author(IAuthor value) {
        this.authorId = value.getAuthorId();
        this.firstName = value.getFirstName();
        this.lastName = value.getLastName();
    }

    public Author(
        Long   authorId,
        String firstName,
        String lastName
    ) {
        this.authorId = authorId;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    @Override
    public Long getAuthorId() {
        return this.authorId;
    }

    @Override
    public Author setAuthorId(Long authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public String getFirstName() {
        return this.firstName;
    }

    @Override
    public Author setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    @Override
    public String getLastName() {
        return this.lastName;
    }

    @Override
    public Author setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Author (");

        sb.append(authorId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IAuthor from) {
        setAuthorId(from.getAuthorId());
        setFirstName(from.getFirstName());
        setLastName(from.getLastName());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IAuthor> E into(E into) {
        into.from(this);
        return into;
    }

    public Author(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
