/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.pojos;


import com.ns.vertx.pg.jooq.tables.interfaces.IAuthorBook;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorBook implements VertxPojo, IAuthorBook {

    private static final long serialVersionUID = -638850107;

    private Long authorId;
    private Long bookId;

    public AuthorBook() {}

    public AuthorBook(IAuthorBook value) {
        this.authorId = value.getAuthorId();
        this.bookId = value.getBookId();
    }

    public AuthorBook(
        Long authorId,
        Long bookId
    ) {
        this.authorId = authorId;
        this.bookId = bookId;
    }

    @Override
    public Long getAuthorId() {
        return this.authorId;
    }

    @Override
    public AuthorBook setAuthorId(Long authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public Long getBookId() {
        return this.bookId;
    }

    @Override
    public AuthorBook setBookId(Long bookId) {
        this.bookId = bookId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthorBook (");

        sb.append(authorId);
        sb.append(", ").append(bookId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAuthorBook from) {
        setAuthorId(from.getAuthorId());
        setBookId(from.getBookId());
    }

    @Override
    public <E extends IAuthorBook> E into(E into) {
        into.from(this);
        return into;
    }

    public AuthorBook(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
