/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.pojos;


import com.ns.vertx.pg.jooq.tables.interfaces.IBook;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements VertxPojo, IBook {

    private static final long serialVersionUID = 709391064;

    private Long    bookId;
    private String  title;
    private Double  price;
    private Integer amount;
    private Boolean isDeleted;

    public Book() {}

    public Book(IBook value) {
        this.bookId = value.getBookId();
        this.title = value.getTitle();
        this.price = value.getPrice();
        this.amount = value.getAmount();
        this.isDeleted = value.getIsDeleted();
    }

    public Book(
        Long    bookId,
        String  title,
        Double  price,
        Integer amount,
        Boolean isDeleted
    ) {
        this.bookId = bookId;
        this.title = title;
        this.price = price;
        this.amount = amount;
        this.isDeleted = isDeleted;
    }

    @Override
    public Long getBookId() {
        return this.bookId;
    }

    @Override
    public Book setBookId(Long bookId) {
        this.bookId = bookId;
        return this;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public Book setTitle(String title) {
        this.title = title;
        return this;
    }

    @Override
    public Double getPrice() {
        return this.price;
    }

    @Override
    public Book setPrice(Double price) {
        this.price = price;
        return this;
    }

    @Override
    public Integer getAmount() {
        return this.amount;
    }

    @Override
    public Book setAmount(Integer amount) {
        this.amount = amount;
        return this;
    }

    @Override
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    @Override
    public Book setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(bookId);
        sb.append(", ").append(title);
        sb.append(", ").append(price);
        sb.append(", ").append(amount);
        sb.append(", ").append(isDeleted);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBook from) {
        setBookId(from.getBookId());
        setTitle(from.getTitle());
        setPrice(from.getPrice());
        setAmount(from.getAmount());
        setIsDeleted(from.getIsDeleted());
    }

    @Override
    public <E extends IBook> E into(E into) {
        into.from(this);
        return into;
    }

    public Book(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
