/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.pojos;


import com.ns.vertx.pg.jooq.tables.interfaces.IOrderItem;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderItem implements VertxPojo, IOrderItem {

    private static final long serialVersionUID = -2091226013;

    private Long    orderItemId;
    private Integer amount;
    private Long    bookId;
    private Long    orderId;

    public OrderItem() {}

    public OrderItem(IOrderItem value) {
        this.orderItemId = value.getOrderItemId();
        this.amount = value.getAmount();
        this.bookId = value.getBookId();
        this.orderId = value.getOrderId();
    }

    public OrderItem(
        Long    orderItemId,
        Integer amount,
        Long    bookId,
        Long    orderId
    ) {
        this.orderItemId = orderItemId;
        this.amount = amount;
        this.bookId = bookId;
        this.orderId = orderId;
    }

    @Override
    public Long getOrderItemId() {
        return this.orderItemId;
    }

    @Override
    public OrderItem setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
        return this;
    }

    @Override
    public Integer getAmount() {
        return this.amount;
    }

    @Override
    public OrderItem setAmount(Integer amount) {
        this.amount = amount;
        return this;
    }

    @Override
    public Long getBookId() {
        return this.bookId;
    }

    @Override
    public OrderItem setBookId(Long bookId) {
        this.bookId = bookId;
        return this;
    }

    @Override
    public Long getOrderId() {
        return this.orderId;
    }

    @Override
    public OrderItem setOrderId(Long orderId) {
        this.orderId = orderId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderItem (");

        sb.append(orderItemId);
        sb.append(", ").append(amount);
        sb.append(", ").append(bookId);
        sb.append(", ").append(orderId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IOrderItem from) {
        setOrderItemId(from.getOrderItemId());
        setAmount(from.getAmount());
        setBookId(from.getBookId());
        setOrderId(from.getOrderId());
    }

    @Override
    public <E extends IOrderItem> E into(E into) {
        into.from(this);
        return into;
    }

    public OrderItem(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
