/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.pojos;


import com.ns.vertx.pg.jooq.tables.interfaces.IOrders;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders implements VertxPojo, IOrders {

    private static final long serialVersionUID = 1119610166;

    private Long          orderId;
    private Double        total;
    private LocalDateTime orderDate;
    private Long          userId;

    public Orders() {}

    public Orders(IOrders value) {
        this.orderId = value.getOrderId();
        this.total = value.getTotal();
        this.orderDate = value.getOrderDate();
        this.userId = value.getUserId();
    }

    public Orders(
        Long          orderId,
        Double        total,
        LocalDateTime orderDate,
        Long          userId
    ) {
        this.orderId = orderId;
        this.total = total;
        this.orderDate = orderDate;
        this.userId = userId;
    }

    @Override
    public Long getOrderId() {
        return this.orderId;
    }

    @Override
    public Orders setOrderId(Long orderId) {
        this.orderId = orderId;
        return this;
    }

    @Override
    public Double getTotal() {
        return this.total;
    }

    @Override
    public Orders setTotal(Double total) {
        this.total = total;
        return this;
    }

    @Override
    public LocalDateTime getOrderDate() {
        return this.orderDate;
    }

    @Override
    public Orders setOrderDate(LocalDateTime orderDate) {
        this.orderDate = orderDate;
        return this;
    }

    @Override
    public Long getUserId() {
        return this.userId;
    }

    @Override
    public Orders setUserId(Long userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orders (");

        sb.append(orderId);
        sb.append(", ").append(total);
        sb.append(", ").append(orderDate);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IOrders from) {
        setOrderId(from.getOrderId());
        setTotal(from.getTotal());
        setOrderDate(from.getOrderDate());
        setUserId(from.getUserId());
    }

    @Override
    public <E extends IOrders> E into(E into) {
        into.from(this);
        return into;
    }

    public Orders(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
