/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.pojos;


import com.ns.vertx.pg.jooq.tables.interfaces.IOrders;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders implements VertxPojo, IOrders {

    private static final long serialVersionUID = 83533968;

    private Long    orderId;
    private Double  total;
    private Date    orderDate;
    private Integer userId;

    public Orders() {}

    public Orders(IOrders value) {
        this.orderId = value.getOrderId();
        this.total = value.getTotal();
        this.orderDate = value.getOrderDate();
        this.userId = value.getUserId();
    }

    public Orders(
        Long    orderId,
        Double  total,
        Date    orderDate,
        Integer userId
    ) {
        this.orderId = orderId;
        this.total = total;
        this.orderDate = orderDate;
        this.userId = userId;
    }

    @Override
    public Long getOrderId() {
        return this.orderId;
    }

    @Override
    public Orders setOrderId(Long orderId) {
        this.orderId = orderId;
        return this;
    }

    @Override
    public Double getTotal() {
        return this.total;
    }

    @Override
    public Orders setTotal(Double total) {
        this.total = total;
        return this;
    }

    @Override
    public Date getOrderDate() {
        return this.orderDate;
    }

    @Override
    public Orders setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
        return this;
    }

    @Override
    public Integer getUserId() {
        return this.userId;
    }

    @Override
    public Orders setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orders (");

        sb.append(orderId);
        sb.append(", ").append(total);
        sb.append(", ").append(orderDate);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IOrders from) {
        setOrderId(from.getOrderId());
        setTotal(from.getTotal());
        setOrderDate(from.getOrderDate());
        setUserId(from.getUserId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IOrders> E into(E into) {
        into.from(this);
        return into;
    }

    public Orders(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
