/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.pojos;


import com.ns.vertx.pg.jooq.tables.interfaces.IRole;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements VertxPojo, IRole {

    private static final long serialVersionUID = 4453560;

    private Long   roleId;
    private String name;

    public Role() {}

    public Role(IRole value) {
        this.roleId = value.getRoleId();
        this.name = value.getName();
    }

    public Role(
        Long   roleId,
        String name
    ) {
        this.roleId = roleId;
        this.name = name;
    }

    @Override
    public Long getRoleId() {
        return this.roleId;
    }

    @Override
    public Role setRoleId(Long roleId) {
        this.roleId = roleId;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public Role setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(roleId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IRole from) {
        setRoleId(from.getRoleId());
        setName(from.getName());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IRole> E into(E into) {
        into.from(this);
        return into;
    }

    public Role(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
