/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.pojos;


import com.ns.vertx.pg.jooq.tables.interfaces.IUsers;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements VertxPojo, IUsers {

    private static final long serialVersionUID = -1797501662;

    private Long    userId;
    private String  firstName;
    private String  lastName;
    private String  email;
    private String  username;
    private String  password;
    private Integer roleId;

    public Users() {}

    public Users(IUsers value) {
        this.userId = value.getUserId();
        this.firstName = value.getFirstName();
        this.lastName = value.getLastName();
        this.email = value.getEmail();
        this.username = value.getUsername();
        this.password = value.getPassword();
        this.roleId = value.getRoleId();
    }

    public Users(
        Long    userId,
        String  firstName,
        String  lastName,
        String  email,
        String  username,
        String  password,
        Integer roleId
    ) {
        this.userId = userId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.username = username;
        this.password = password;
        this.roleId = roleId;
    }

    @Override
    public Long getUserId() {
        return this.userId;
    }

    @Override
    public Users setUserId(Long userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public String getFirstName() {
        return this.firstName;
    }

    @Override
    public Users setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    @Override
    public String getLastName() {
        return this.lastName;
    }

    @Override
    public Users setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public Users setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public String getUsername() {
        return this.username;
    }

    @Override
    public Users setUsername(String username) {
        this.username = username;
        return this;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public Users setPassword(String password) {
        this.password = password;
        return this;
    }

    @Override
    public Integer getRoleId() {
        return this.roleId;
    }

    @Override
    public Users setRoleId(Integer roleId) {
        this.roleId = roleId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(email);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUsers from) {
        setUserId(from.getUserId());
        setFirstName(from.getFirstName());
        setLastName(from.getLastName());
        setEmail(from.getEmail());
        setUsername(from.getUsername());
        setPassword(from.getPassword());
        setRoleId(from.getRoleId());
    }

    @Override
    public <E extends IUsers> E into(E into) {
        into.from(this);
        return into;
    }

    public Users(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
