/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.tables.records;


import com.ns.vertx.pg.jooq.tables.OrderItem;
import com.ns.vertx.pg.jooq.tables.interfaces.IOrderItem;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderItemRecord extends UpdatableRecordImpl<OrderItemRecord> implements VertxPojo, Record4<Long, Integer, Long, Long>, IOrderItem {

    private static final long serialVersionUID = 275380799;

    /**
     * Setter for <code>public.order_item.order_item_id</code>.
     */
    @Override
    public OrderItemRecord setOrderItemId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.order_item.order_item_id</code>.
     */
    @Override
    public Long getOrderItemId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.order_item.amount</code>.
     */
    @Override
    public OrderItemRecord setAmount(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.order_item.amount</code>.
     */
    @Override
    public Integer getAmount() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.order_item.book_id</code>.
     */
    @Override
    public OrderItemRecord setBookId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.order_item.book_id</code>.
     */
    @Override
    public Long getBookId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.order_item.order_id</code>.
     */
    @Override
    public OrderItemRecord setOrderId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.order_item.order_id</code>.
     */
    @Override
    public Long getOrderId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Integer, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Integer, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OrderItem.ORDER_ITEM.ORDER_ITEM_ID;
    }

    @Override
    public Field<Integer> field2() {
        return OrderItem.ORDER_ITEM.AMOUNT;
    }

    @Override
    public Field<Long> field3() {
        return OrderItem.ORDER_ITEM.BOOK_ID;
    }

    @Override
    public Field<Long> field4() {
        return OrderItem.ORDER_ITEM.ORDER_ID;
    }

    @Override
    public Long component1() {
        return getOrderItemId();
    }

    @Override
    public Integer component2() {
        return getAmount();
    }

    @Override
    public Long component3() {
        return getBookId();
    }

    @Override
    public Long component4() {
        return getOrderId();
    }

    @Override
    public Long value1() {
        return getOrderItemId();
    }

    @Override
    public Integer value2() {
        return getAmount();
    }

    @Override
    public Long value3() {
        return getBookId();
    }

    @Override
    public Long value4() {
        return getOrderId();
    }

    @Override
    public OrderItemRecord value1(Long value) {
        setOrderItemId(value);
        return this;
    }

    @Override
    public OrderItemRecord value2(Integer value) {
        setAmount(value);
        return this;
    }

    @Override
    public OrderItemRecord value3(Long value) {
        setBookId(value);
        return this;
    }

    @Override
    public OrderItemRecord value4(Long value) {
        setOrderId(value);
        return this;
    }

    @Override
    public OrderItemRecord values(Long value1, Integer value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IOrderItem from) {
        setOrderItemId(from.getOrderItemId());
        setAmount(from.getAmount());
        setBookId(from.getBookId());
        setOrderId(from.getOrderId());
    }

    @Override
    public <E extends IOrderItem> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderItemRecord
     */
    public OrderItemRecord() {
        super(OrderItem.ORDER_ITEM);
    }

    /**
     * Create a detached, initialised OrderItemRecord
     */
    public OrderItemRecord(Long orderItemId, Integer amount, Long bookId, Long orderId) {
        super(OrderItem.ORDER_ITEM);

        set(0, orderItemId);
        set(1, amount);
        set(2, bookId);
        set(3, orderId);
    }

    public OrderItemRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
