/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.routines;


import com.ns.vertx.pg.jooq.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetOrderitemByOiId2 extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1710927038;

    /**
     * The parameter <code>public.get_orderitem_by_oi_id2.oi_id</code>.
     */
    public static final Parameter<Long> OI_ID = Internal.createParameter("oi_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public GetOrderitemByOiId2() {
        super("get_orderitem_by_oi_id2", Public.PUBLIC);

        addInParameter(OI_ID);
    }

    /**
     * Set the <code>oi_id</code> parameter IN value to the routine
     */
    public void setOiId(Long value) {
        setValue(OI_ID, value);
    }
}
