/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.routines;


import com.ns.vertx.pg.jooq.Public;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetOrderitemByOiId extends AbstractRoutine<JSON> {

    private static final long serialVersionUID = 48790423;

    /**
     * The parameter <code>public.get_orderitem_by_oi_id.RETURN_VALUE</code>.
     */
    public static final Parameter<JSON> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.JSON, false, false);

    /**
     * The parameter <code>public.get_orderitem_by_oi_id.oi_id</code>.
     */
    public static final Parameter<Long> OI_ID = Internal.createParameter("oi_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public GetOrderitemByOiId() {
        super("get_orderitem_by_oi_id", Public.PUBLIC, org.jooq.impl.SQLDataType.JSON);

        setReturnParameter(RETURN_VALUE);
        addInParameter(OI_ID);
    }

    /**
     * Set the <code>oi_id</code> parameter IN value to the routine
     */
    public void setOiId(Long value) {
        setValue(OI_ID, value);
    }

    /**
     * Set the <code>oi_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public GetOrderitemByOiId setOiId(Field<Long> field) {
        setField(OI_ID, field);
        return this;
    }
}
