/*
 * This file is generated by jOOQ.
 */
package com.ns.vertx.pg.jooq.routines;


import com.ns.vertx.pg.jooq.Public;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetOrderByOrderId8 extends AbstractRoutine<JSON> {

    private static final long serialVersionUID = 1908637607;

    /**
     * The parameter <code>public.get_order_by_order_id8.RETURN_VALUE</code>.
     */
    public static final Parameter<JSON> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.JSON, false, false);

    /**
     * The parameter <code>public.get_order_by_order_id8.o_id</code>.
     */
    public static final Parameter<Long> O_ID = Internal.createParameter("o_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public GetOrderByOrderId8() {
        super("get_order_by_order_id8", Public.PUBLIC, org.jooq.impl.SQLDataType.JSON);

        setReturnParameter(RETURN_VALUE);
        addInParameter(O_ID);
    }

    /**
     * Set the <code>o_id</code> parameter IN value to the routine
     */
    public void setOId(Long value) {
        setValue(O_ID, value);
    }

    /**
     * Set the <code>o_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public GetOrderByOrderId8 setOId(Field<Long> field) {
        setField(O_ID, field);
        return this;
    }
}
